README.md, backends/candle/src/lib.rs, router/src/main.rs
=> feat: support camembert

README.md, backends/candle/src/lib.rs, router/src/main.rs
+ (11/5/23) I tested on the CPU env with my RoBERTa model.
* OS : Windows 10
* CPU : i7-7700K
* rustc : v1.73.0 stable
* build : `cargo install --path router -F candle -F mkl`
`roberta-large` model & tokenizer.
* pooling : cls
* type : float32 (default)
code
```
model = ...
with torch.inference_mode():
token = tokenizer(
['asdf'],
truncation=True,
return_tensors='pt',
)
pytorch_embedding = model(**token)[0].numpy()  # shape: (1024,)
tei_embedding = np.asarray(
requests.post(
'http://localhost:8080/embed', 
data=json.dumps({'inputs': 'asdf'}), 
headers={'Content-type': 'application/json'},
).json(),
dtype=np.float32,
)[0, :]  # shape: (1024,)
np.testing.assert_allclose(
pytorch_embedding,
tei_embedding,
rtol=1e-4,
atol=1e-4,
)
```
maybe, it's due to intel-mkl or type casting (f64, f32) …
=> feat: support roberta

docs/source/en/index.md
For consistency with other repos, doc images have been uploaded to [https://huggingface.co/datasets/huggingface/documentation-images/](https://huggingface.co/datasets/huggingface/documentation-images/). Thus, links on index.md have been updated.
=> [docs] Images links updated

docs/index.html
Just fixes inappropriate title of API docs page.
=> fix: fix inappropriate title of API docs page

Dockerfile, Dockerfile-cuda
#90 introduced regression to non-grpc build - server fails to start and complains "You must use one of `http` or `grpc`". This is due to the http feature flag is not turned on in the Dockerfile. This PR fixes that.
=> fix: enable http feature in http-builder

Cargo.lock, load_tests/load.js, router/Cargo.toml, router/src/http/server.rs, router/src/lib.rs, router/src/main.rs
See https://github.com/hyperium/hyper/issues/1790
Close #156
=> fix: use mimalloc to solve memory "leak"

Dockerfile
The base image doesn't have curl or wget installed, so we cannot do health checks when this is deployed as a service (for example, in AWS ECS, which is my use case).
I propose installing `curl` to be able to make container health checks like: `curl -f http://localhost:8080/health || exit 1`.
Thanks!
@OlivierDehaene
=> Update Dockerfile to install curl

Dockerfile-arm64, README.md
This PR adds a `Dockerfile-arm64` that does build on M1 Macs (and potentially on M2 as well, not tested)
- #46 
- @mneedham
- @OlivierDehaene
=> Add  Dockerfile-arm64 to allow docker builds on Apple M1/M2 architecture

README.md, docs/source/en/cli_arguments.md, router/src/grpc/server.rs, router/src/http/server.rs, router/src/lib.rs, router/src/main.rs
=> feat: add api_key for request authorization

Dockerfile-cuda-all, docs/openapi.json, router/src/http/server.rs, router/src/http/types.rs, router/src/lib.rs, router/tests/common.rs
@drbh what do you think?
@philschmid FYI this will modify the API to:
```
curl 127.0.0.1:3000/vertex \
-X POST \
-d '{"instances": [{"type": "embed", "inputs": "I like you."}]}' \
-H 'Content-Type: application/json'
```
=> feat: add all methods to vertex API

router/src/http/server.rs, router/src/http/types.rs, router/src/lib.rs, router/src/main.rs
=> feat: add auto-truncate arg

.github/workflows/build_75.yaml, .github/workflows/build_80.yaml, .github/workflows/build_86.yaml, .github/workflows/build_89.yaml, .github/workflows/build_90.yaml, .github/workflows/build_all.yaml, .github/workflows/build_cpu.yaml
=> Ci migration to K8s

sagemaker-entrypoint-cuda-all.sh
Cover Nvidia T4 for g4dn instances and L4 GPU for g6 instance
Based on https://developer.nvidia.com/cuda-gpus
=> chore: cover Nvidia T4/L4 GPU

Cargo.lock, backends/candle/Cargo.toml, core/Cargo.toml, router/Cargo.toml
This is necessary in order to load models whose tokenizers have been created by a version after the breaking change
https://github.com/huggingface/tokenizers/pull/1476 (i.e. >= v0.19.0)
Fixes #265 
to it if that's the case. --> #265 
=> Upgrade tokenizers to 0.19.1 to deal with breaking change in tokenizers

README.md, backends/python/server/text_embeddings_server/cli.py, backends/python/server/text_embeddings_server/utils/tracing.py, backends/python/src/lib.rs, backends/python/src/management.rs, backends/src/lib.rs, docs/source/en/cli_arguments.md, router/src/lib.rs, router/src/logging.rs, router/src/main.rs, router/tests/common.rs
related to #283 
@OlivierDehaene OR @Narsil
=> Add env for OTLP service name

.github/workflows/build_75.yaml, .github/workflows/build_80.yaml, .github/workflows/build_86.yaml, .github/workflows/build_89.yaml, .github/workflows/build_90.yaml, .github/workflows/build_all.yaml, .github/workflows/build_cpu.yaml, Dockerfile, README.md
=> Fix CI build timeout

Cargo.lock, Cargo.toml, backends/Cargo.toml, backends/candle/Cargo.toml, backends/core/Cargo.toml, backends/src/lib.rs, core/Cargo.toml, core/src/infer.rs, core/src/queue.rs, core/src/tokenization.rs, load_tests/load.js, load_tests/load_grpc.js, router/Cargo.toml, router/src/grpc/server.rs, router/src/http/server.rs, router/src/lib.rs, router/src/logging.rs, router/src/main.rs, router/src/shutdown.rs
See: https://www.algolia.com/blog/engineering/when-allocators-are-hoarding-your-precious-memory/
related to #156
=> fix: use malloc_trim to cleanup pages

Cargo.lock, core/src/download.rs, core/src/infer.rs, core/src/tokenization.rs, docs/openapi.json, proto/tei.proto, router/src/grpc/server.rs, router/src/http/server.rs, router/src/http/types.rs, router/src/lib.rs, router/src/main.rs, router/tests/common.rs
=> feat: add default prompts

router/src/http/server.rs
This PR adds option value '*' to --cors-allow-origin cli option to allow browser-based apps to use the embedding server directly. This is useful for local deployments of the embeddings inference server.
=> Add optional CORS allow any option value in http server cli

Cargo.lock, docs/openapi.json, router/Cargo.toml, router/src/http/server.rs, router/src/http/types.rs
=> feat: add `/similarity` route

backends/src/lib.rs
Fixes #341
* log warning message instead of throwing an error or panic when failing to download the `model.onnx_data` file because I guess it is optional.
* The below error is out of topic. it failed to download the `model.onnx_data` due to the SSL issue in my environment (Windows 10, WSL2). maybe it's an issue with my env or `cdn-lfs.huggingface.co`, or okay with other environments.
```
2024-07-13T11:13:34.821780Z  INFO download_artifacts: text_embeddings_backend: backends/src/lib.rs:384: Downloading `onnx/model.onnx_data`
2024-07-13T11:14:36.250951Z  WARN download_artifacts: text_embeddings_backend: backends/src/lib.rs:388: Could not download `onnx/model.onnx_data`: request error: request or response body error: error reading a body from connection: error:0A000119:SSL …
```
=> Download `model.onnx_data`

router/src/http/types.rs
This PR adjusts the similarity parameters to use a default for truncation direction 
example request
```bash
curl "http://localhost:3000/similarity" \
-X POST \
-H "Accept: application/json" \
-H "Authorization: Bearer hf_XXXXX" \
-H "Content-Type: application/json" \
-d '{
"inputs": {
"sentences": [
"That is a happy dog",
"That is a very happy person",
"Today is a sunny day"
],
"source_sentence": "That is a happy person"
},
"parameters": {}
}'
```
=> fix: add serde default for truncation direction

router/src/http/server.rs
Fixes #353
* Separate the routers into two groups (one that requires auth and one that doesn't), and apply the auth middleware only for the group.
```
$ curl -Is http://127.0.0.1:8081/health
HTTP/1.1 401 Unauthorized
content-length: 0
date: Fri, 26 Jul 2024 16:24:33 GMT
```
```
$ curl -Is http://127.0.0.1:8081/health -H 'Authorization: Bearer asdf'
HTTP/1.1 200 OK
content-length: 0
vary: origin, access-control-request-method, access-control-request-headers
access-control-allow-origin: *
date: Fri, 26 Jul 2024 16:24:41 GMT
```
```
$ curl -Is http://127.0.0.1:8080/health
HTTP/1.1 200 OK
content-length: 0
vary: origin, access-control-request-method, access-control-request-headers
access-control-allow-origin: *
date: Fri, 26 Jul 2024 16:24:52 GMT
```
to it if that's the …
=> Fix to allow health check w/o auth

Cargo.lock, backends/ort/Cargo.toml
Fixes #355
* i guess IR version 10 is supported from onnxruntime 1.8.0, and it is used from `2.0.0-rc.3` version. So, upgrade to the latest version, `2.0.0-rc.4`.
```
$ ./target/release/text-embeddings-router --model-id dunzhang/stella_en_400M_v5 --revision refs/pr/3 --port 8080
2024-07-26T16:50:55.128433Z  INFO text_embeddings_router: router/src/main.rs:175: Args { model_id: "dun*****/******_**_***M_v5", revision: Some("refs/pr/3"), tokenization_workers: None, dtype: None, pooling: None, max_concurrent_requests: 512, max_batch_tokens: 16384, max_batch_requests: None, max_client_batch_size: 32, auto_truncate: false, default_prompt_name: None, default_prompt: None, hf_api_token: None, hostname: "0.0.0.0", port: 8080, uds_path: "/tmp/text-embeddings-inference-server", huggingface_hub_cache: …
```
=> Update `ort` crate version to `2.0.0-rc.4` to support onnx IR version 10

Dockerfile, Dockerfile-cuda, Dockerfile-cuda-all
Also unifies installed packages in base image for all dockers
adds curl install to fix health checks
Fixes issue where healthchecks aren't possible again (a regression first fixed here https://github.com/huggingface/text-embeddings-inference/pull/117)
- [x ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
members/contributors who may …
=> adds curl to fix healthcheck

backends/candle/src/lib.rs, backends/candle/src/models/flash_gte.rs, backends/candle/src/models/gte.rs, backends/candle/src/models/mod.rs, backends/candle/src/models/nomic.rs
I implemented the GTE model to support the non-flash-attn version and tested it's working on the T4 GPU.
* to work with the `gte-multilingual-base`, `config.json` needs some modifications.
* remove `NewModelClassification` from `architectures`.
* remove `new.` prefix from the key of the weight file.
```
./target/release/text-embeddings-router --model-id ./gte-multilingual-base --port 12345 --dtype float32 --pooling cls
2024-11-30T09:07:38.940983Z  INFO text_embeddings_router: router/src/main.rs:175: Args { model_id: "./gte-************-*ase", revision: None, tokenization_workers: None, dtype: Some(Float32), pooling: Some(Cls), max_concurrent_requests: 512, max_batch_tokens: 16384, max_batch_requests: None, max_client_batch_size: 32, auto_truncate: false, default_prompt_name: None, …
```
=> Implement GTE model to support the non-flash-attn version

backends/python/server/text_embeddings_server/models/__init__.py, backends/python/server/text_embeddings_server/models/masked_model.py, backends/python/server/text_embeddings_server/models/pooling.py, backends/python/src/management.rs
As the title says. Follows a modified version of https://github.com/huggingface/tei-gaudi/pull/35. 
Tested using local install and Intel docker on platform HPU using the README example for Splade usage. 
=> Enable splade embeddings for Python backend

router/src/grpc/server.rs, router/src/http/server.rs
Fixes #480 
@OlivierDehaene OR @Narsil
=> Fix double incrementing `te_request_count` metric

.github/workflows/matrix.json
This PR add Intel based images to the CI
The new images will be available at
```
ghcr.io/huggingface/text-embeddings-inference:cpu-ipex-sha-<SHA_COMMIT>
ghcr.io/huggingface/text-embeddings-inference:xpu-ipex-sha-<SHA_COMMIT>
ghcr.io/huggingface/text-embeddings-inference:hpu-sha-<SHA_COMMIT>
```
=> Add intel based images to the CI

.github/workflows/matrix.json
The intel image are currently built as `ghcr.io/huggingface/text-embeddings-inference:hpulatest` instead of `ghcr.io/huggingface/text-embeddings-inference:hpu-latest`
There is a typo in the previous request #518
=> Fix typo on intel docker image

README.md, backends/candle/tests/snapshots/test_gte__snowflake_gte_batch.snap, backends/candle/tests/snapshots/test_gte__snowflake_gte_single.snap, docs/source/en/cli_arguments.md, docs/source/en/private_models.md, router/src/lib.rs, router/src/main.rs
This PR deprecates the `--hf-api-token` argument in favor of `--hf-token`, to be compliant with the standard naming for the Hugging Face token, specially when provided via environment variable as `HF_TOKEN`, but also to be aligned with the `text-generation-inference` counterpart.
@Narsil or @McPatate
=> Use `--hf-token` instead of `--hf-api-token`

.github/workflows/test.yaml, Cargo.lock, Cargo.toml, backends/candle/Cargo.toml, backends/candle/src/models/flash_gte.rs, backends/candle/tests/common.rs, backends/candle/tests/snapshots/test_flash_gte__gte_classification_single.snap, backends/candle/tests/test_flash_bert.rs, backends/candle/tests/test_flash_qwen2.rs, backends/src/lib.rs, flake.lock, flake.nix, router/Cargo.toml, router/tests/test_http_embed.rs, router/tests/test_http_predict.rs, router/tests/test_http_rerank.rs, rust-toolchain.toml
=> Fixing the tests.

README.md, docs/source/en/cli_arguments.md, router/src/logging.rs, router/src/main.rs
Adds a CLI flag, `disable-spans` (or environment variable `DISABLE_SPANS`) to remove the spans list and current span from the log trace when enabled. In production environments, the span's trace could contain sensitive user information, so this feature would be crucial for security compliance.
to it if that's the case. (https://github.com/huggingface/text-embeddings-inference/issues/483)
- …
=> add CLI flag `disable-spans` to toggle span trace logging

Cargo.lock, backends/candle/Cargo.toml, backends/candle/tests/common.rs, router/src/lib.rs
Hey! Big thanks for this awesome project. But because of network problems, I've been manually downloading models and mounting them. It's a real pain, especially when I want to try out new models. So, I thought I'd make some changes to make things easier for users like me.
This PR bumps up the `hf-hub` version ([release note](https://github.com/huggingface/hf-hub/releases/tag/v0.4.0)) and tweaks the related code to support using the `HF_ENDPOINT` environment variable. This way, we can use mirrors for downloading, which should speed things up and make it more reliable, especially in bad network env.
By the way, fix #416
Maybe the documentation should also be updated, but I'm not sure if my changes are appropriate to go on...
[documentation …
=> feat: support HF_ENDPOINT environment when downloading model

backends/python/server/text_embeddings_server/models/__init__.py
@regisss @Narsil pls help review
=> make a WA in case Bert model do not have `safetensor` file

Dockerfile-intel
This PR fixes the `FromAsCasing` warning on `Dockerfile-intel` so as to go from `FROM ... as ...` into `FROM ... AS ...` which is the standard. This PR doesn't solve anything critical, but rather annoying (see screenshot below).
@Narsil or @baptistecolle
=> Fix `FromAsCasing` warning in `Dockerfile-intel`

Cargo.lock, Cargo.toml, Dockerfile-intel, backends/candle/src/models/gte.rs
=> Prepare for release.

backends/candle/src/models/flash_qwen2.rs, backends/candle/src/models/qwen2.rs
This PR makes the `sliding_window` to be `Option<usize>` instead of `usize` as it can be set to `null`; additionally, the `model` prefix is only pushed for `FlashQwen2` if available, as the `Qwen2` model does not come with the prefix since it's an instance of `Qwen2Model` not `Qwen2ModelForCausalLM`, meaning that it doesn't have neither the `lm_head` nor the `model` prefix.
This PR then enables models as e.g. https://huggingface.co/mims-harvard/ToolRAG-T1-GTE-Qwen2-1.5B (also Azure asked us to add support for this model and a recent discussion has been opened at https://huggingface.co/mims-harvard/ToolRAG-T1-GTE-Qwen2-1.5B/discussions/1, which is unrelated as they are trying to use TGI instead of TEI, but that would unlock serving this model).
@Narsil (and @pagezyhf for context on the …
=> Make `sliding_window` for `Qwen2` optional

backends/python/server/text_embeddings_server/models/flash_bert.py, backends/python/server/text_embeddings_server/utils/flash_attn.py
Using model `WhereIsAI/UAE-Large-V1` to do a benchmark, this implementation can get ~1.06x throughput than original one
=> Optimize the performance of FlashBert on HPU by using fast mode softmax

README.md, docs/source/en/cli_arguments.md
This PR fixes a typo in `--hf-token` as it was still pointing to the to-be-deprecated `--hf-api-token` argument, and also fixes the indentation of the `-p/--port` argument when showed as the `text-embeddings-inference --help` output.
P.S. I recall this was dynamically generated in text-generation-inference, right @Narsil?
@Narsil
=> Fix typos / formatting in CLI args in Markdown files

backends/candle/src/lib.rs, backends/candle/src/models/flash_modernbert.rs, backends/candle/src/models/modernbert.rs, backends/grpc-client/build.rs, flake.nix
Fixes ModernBert to use flash attention when possible.
=> Fixing FlashAttention ModernBert.

backends/candle/src/models/bert.rs, backends/candle/src/models/distilbert.rs
This PR fixes an issue preventing loading BERT and DistilBERT models with the SPLADE pooling, as when converting the `pytorch_model.bin` into a `model.safetensors` files, the tensors with shared memory for the content are removed for safety, meaning that the required weights for the SPLADE head were not there, as support for SPLADE was originally introduced for the models at https://huggingface.co/naver which are indeed `pytorch_model.bin` files.
So on, this PR bypasses that by adding a check on whether the required tensors are there, and if not, it falls back to the tensor with the shared memory instead.
To reproduce the issue, simply grab any model under https://huggingface.co/naver as e.g. `naver/efficient-splade-V-large-query` and download the `pytorch_model.bin` file and then convert …
=> Fix `{Bert,DistilBert}SpladeHead` when loading from Safetensors

README.md, docs/source/en/supported_models.md
This PR updates the `README.md` to update the references to the `ghcr.io/huggingface/text-embeddings-inference` container to the latest i.e. 1.7, as well as fixing the table ordering. After that, then the `docs/source/en/supported_models.md` file has been updated accordingly in order to be aligned with the `README.md` since it was outdated and pointing to outdated revision branches for the re-rankers, and not aligned with the `README.md`.
@Narsil or @McPatate
=> Update `README.md` and `supported_models.md`

Cargo.lock, docs/source/en/quick_tour.md
=> Back with linting.

docs/source/en/_toctree.yml, docs/source/en/tei_cloud_run.md
This PR adds an example to the docs on how to deploy TEI on Google's Cloud Run.
This is largely a copy of the [amazing guide on deploying TGI](https://huggingface.co/docs/google-cloud/en/examples/cloud-run-deploy-gemma-2-on-cloud-run) by @alvarobartt but adapted for TEI.
To do:
=> [Docs] Add cloud run example

.github/workflows/build.yaml, .github/workflows/liniting.yaml, .github/workflows/test.yaml, Dockerfile, Dockerfile-cuda, Dockerfile-cuda-all, Dockerfile-intel
This PR bumps the `sccache` and `sccache-action` versions to 0.10.0 and 0.0.9, respectively; in order to bypass the deprecation reported at https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts, affecting `sccache`.
This PR applies the following changes:
- Bump `sccache` in both GitHub Actions and Dockerfiles to 0.10.0
- Rename `ACTIONS_CACHE_URL` to `ACTIONS_RESULTS_URL` as per https://github.com/mozilla/sccache/issues/2351
- Bump `sccache-action` to 0.0.9 (including the pinning for the `sccache` version to 0.10.0)
@XciD or @Narsil
=> Bump `sccache` to 0.10.0 and `sccache-action` to 0.0.9

backends/python/server/text_embeddings_server/models/flash_bert.py
Use `WhereIsAI/UAE-Large-V1` model to do  benchmark, below is the throughput(seq/s) comparison:
| bs | before | after |
|-----|-----|-----|
| 1 | 199.65 | 219.61 |
| 2 | 239.61 | 284.78 |
| 4 | 321.37 | 373.13 |
| 8 | 506.40 | 549.61 |
| 16 | 759.07 | 822.17 |
| 32 | 1028.31 | 1285.57 |
| 64 | 1130.67 | 1708.73 |
| 128 | OOM | 1030.06 |
=> optimize the performance of FlashBert Path for HPU

router/src/http/server.rs, router/src/logging.rs
Fixes #374
I made a simple middleware to extract OpenTelemetry context (e.g. trace id, span id) from request headers. When valid transparent info is provided, then, it'll gonna use that context to create the span (if not, it'll generate its own as it does currently).
@OlivierDehaene OR @Narsil
=> Get opentelemetry trace id from request headers

README.md, router/src/lib.rs, router/src/main.rs, router/src/prometheus.rs
Allow configuring Prometheus port via argument (and environment variable)
Fixes #499
@Narsil, @alvarobartt
=> Add argument for configuring Prometheus port

README.md, backends/candle/src/models/modernbert.rs, backends/candle/tests/snapshots/test_modernbert__modernbert_classification_single.snap, backends/candle/tests/test_modernbert.rs
Adding the missing `head.` prefix in the key name of the weight in the `ModernBertClassificationhead`. and adding the test case.
```
text-embeddings-router --model-id ../gte-reranker-modernbert-base/ --pooling cls --port 8080 --dtype float32 --auto-truncate
2025-04-18T06:51:43.264617Z  INFO text_embeddings_router: router/src/main.rs:185: Args { model_id: "../gte-********-**********-*ase/", revision: None, tokenization_workers: None, dtype: Some(Float32), pooling: Some(Cls), max_concurrent_requests: 512, max_batch_tokens: 16384, max_batch_requests: None, max_client_batch_size: 32, auto_truncate: true, default_prompt_name: None, default_prompt: None, hf_api_token: None, hf_token: None, hostname: "0.0.0.0", port: 8080, uds_path: "/tmp/text-embeddings-inference-server", huggingface_hub_cache: …
```
=> Adding missing `head.` prefix in the weight name in `ModernBertClassificationHead`

backends/python/server/text_embeddings_server/models/__init__.py, backends/python/server/text_embeddings_server/models/flash_mistral.py, backends/python/server/text_embeddings_server/utils/flash_attn.py
This PR enables op level optimizations for Mistral type model. Currently it supports HPU device, and can get best throughput from 124 sentence/s to 133 sentences/s compared with Optimum-habana modeling, (We use `Salesforce/SFR-Embedding-2_R` for benchmark.)
=> enable flash mistral model for HPU device

router/src/main.rs
Fixes #601 which appears to be a regression caused by #589.
=> Remove duplicate short option '-p' to fix router executable

README.md, docs/source/en/cli_arguments.md
This PR is a follow up of #602, that updates the `text-embeddings-router --help` output to include the latest arguments, and also to fix the `PROMETHEUS_PORT` environment variable value that was misleading and previously set to `PORT` too.
@Narsil
=> Update `text-embeddings-router --help` output

router/src/http/server.rs, router/src/lib.rs, router/src/logging.rs, router/tests/common.rs
=> Warmup padded models too.

backends/candle/src/models/gte.rs, backends/candle/tests/snapshots/test_flash_gte__gte_classification_single.snap, backends/candle/tests/snapshots/test_gte__gte_classification_single.snap, backends/candle/tests/test_gte.rs
Fixes #605
The `pooler` layer loads its weight using an incorrect key name, causing the classifier and reranker based on GTE to produce wrong outputs.
I've checked that the outputs are aligned with the HF models.
@Narsil @alvarobartt
=> Fix the weight name in GTEClassificationHead

backends/candle/src/models/flash_modernbert.rs, backends/candle/src/models/modernbert.rs, backends/candle/tests/snapshots/test_modernbert__modernbert_classification_mean_pooling.snap.new, backends/candle/tests/snapshots/test_modernbert__modernbert_classifier_mean_pooling.snap, backends/candle/tests/test_modernbert.rs, backends/core/src/lib.rs
Apologies in advance, new this this area and Rust 😅.
I noticed differences between Transformers and TEI libraries when running rerankers with a `mean` classifier pooling strategy. [More details here](https://github.com/huggingface/text-embeddings-inference/issues/615).
Fixes https://github.com/huggingface/text-embeddings-inference/issues/615
Not sure who might be best to review 😄  @OlivierDehaene OR @Narsil
=> Add mean pooling strategy for Modernbert classifier

backends/candle/src/layers/linear.rs, backends/candle/src/models/flash_jina.rs, backends/candle/src/models/flash_jina_code.rs, backends/candle/src/models/flash_mistral.rs, backends/candle/src/models/flash_qwen2.rs, backends/candle/src/models/jina.rs, backends/candle/src/models/jina_code.rs, backends/candle/src/models/modernbert.rs
TL;DR Leverage `HiddenAct.forward` and handle SiLU and SwiGLU separately
This PR fixes the `forward` method in the `HiddenAct` implementation to use the SiLU activation when the activation is SwiGLU, since SwiGLU is SiLU + down projection to half the size since it's split on the intermediate dimension (as per https://github.com/huggingface/candle/blob/17313a4226a6c6bde444d28b4be4f0f96d155be7/candle-nn/src/ops.rs#L44-L47), and since `candle` brings an implementation for it, then the `serde` alias for `Silu` has been removed to handle separately both Silu and Swiglu.
Additionally, to unify the codebase, this PR leverages the `forward` method in `HiddenAct` instead of the previous `match self.act`.
Fixes #629
@kozistr since they recently introduced the `forward` method in `HiddenAct` and …
=> Add `HiddenAct::Silu` (remove `serde` alias)

backends/candle/src/models/qwen3.rs
=> Fixing metal backend.

backends/ort/src/lib.rs
I really wanted to use a quantized Qwen3-Embedding model, this let me do it.
=> Add last token pooling support for ORT.

backends/candle/src/models/qwen3.rs, backends/src/lib.rs
Without this, batches were erroring on CPU because it was trying to compare the F32 attention mask with the F16 output tensors.
=> Fix Qwen3 Embedding Float16 DType

Cargo.lock, Cargo.toml, README.md, docs/source/en/private_models.md, docs/source/en/quick_tour.md, docs/source/en/supported_models.md
This PR updates the `version` in `Cargo.toml` before the 1.8.0 release, as well as updating the references to the containers published under `ghcr.io/huggingface/text-embeddings-inference` from 1.7 to 1.8.
This release includes support for newer architectures such as Qwen3, as well as Dense module and Matryoka Representation Learning (MRL) support, along with other bug fixes and improvements overall.
@Narsil
=> Update `version` to 1.8.0

backends/candle/src/lib.rs
This PR handles the value for the environment variable `USE_FLASH_ATTENTION` when applicable, so that Flash Attention can be disabled, as it's known to be problematic on Turing.
This being said, even if the `USE_FLASH_ATTENTION` environment variable was already there, it was not handled for some cases such as Qwen2, Qwen3, or GTE; neither for Mistral which won't support it, but still raising an error if provided.
Fixes #644 #347
@Narsil
Maybe it's a nice time to update the documentation around this issue, as there are similar reports of numerical instability / null or empty vectors when running on Turing, which is expected, but maybe the documentation could be more clear around it if so many users report the same issues; which I can do as part of this PR if needed 🤗
=> Disable Flash Attention with `USE_FLASH_ATTENTION`

Cargo.lock, backends/ort/Cargo.toml, backends/ort/src/lib.rs, backends/src/lib.rs
This PR updates how the `ort` inputs are being handled to extend support for optional values such as `position_ids` or `past_key_values`.
e.g. `onnx-community/Qwen3-Embedding-0.6B-ONNX` has been now enabled on Text Embeddings Inference (TEI) via `ort` thanks to the conditional addition of the `past_key_values` if amongst the inputs, to leverage the optimized Multi-head Attention (MHA) nodes that do require those inputs, so now one could run the following (whereas with the version in `main` it would fail with missing inputs on `past_key_values`):
```bash
cargo run --release --features ort,http --no-default-features -- --model-id onnx-community/Qwen3-Embedding-0.6B-ONNX --dtype float32 --pooling last-token
```
> [!NOTE]
> On a subsequent PR, both the input building and the pooling …
=> Add support for `position_ids` and `past_key_values` in `OrtBackend`

docs/openapi.json
This PR updates the `docs/openapi.json` file, automatically generated by `utoipa` and manually uploaded into this repository.
The `openapi.json` is rendered automatically in https://huggingface.github.io/text-embeddings-inference/, and should be updated as part of the release process in PRs as e.g. #686 from now on.
@Narsil
=> Update `docs/openapi.json` for v1.8.0

docs/source/en/quick_tour.md
**docs(tei): fix OpenAI client usage example for embeddings**
---
This PR updates the documentation for using the OpenAI Python client with TEI’s OpenAI-compatible API.
The previous example incorrectly set the `base_url` to `/v1/embeddings`, which caused errors.
It also did not mention that the OpenAI client requires an `api_key` argument (even if unused by TEI).
**Changes made:**
* Corrected the `base_url` to `http://localhost:8080/v1`
* Added `api_key="fake"` to satisfy the OpenAI client requirements
* Updated the example to print `response.data[0].embedding` for clarity
**Motivation:**
Improve usability of the TEI docs by providing a working out-of-the-box example for developers who want to use the OpenAI client with TEI.
**Fixes:**
N/A (documentation improvement)
---
---
Tagging …
=> Fix OpenAI client usage example for embeddings

router/src/lib.rs
Fixes #723
Fixes #694
* Raise an error when `max_input_length` is bigger than `max_batch_tokens` and `auto-truncate` is disabled.
* Reduce `max_input_length` to `max_batch_tokens` when `auto-truncate` is enabled.
Feel free to let me know whether this approach would be proper or not 🤗
```
./target/release/text-embeddings-router --model-id ../Qwen3-Embedding-0.6B/ --pooling last-token --port 8080 --dtype float32 --max-batch-tokens 1024
2025-09-20T10:05:20.198290Z  INFO text_embeddings_router: router/src/main.rs:203: Args { model_id: "../Qwe**-*********-0.6B/", revision: None, tokenization_workers: None, dtype: Some(Float32), pooling: Some(LastToken), max_concurrent_requests: 512, max_batch_tokens: 1024, max_batch_requests: None, max_client_batch_size: 32, auto_truncate: false, …
```
=> Fix the infinite loop when `max_input_length` is bigger than `max-batch-tokens`

README.md, docs/source/en/local_gpu.md
This PR fixes the `cargo install --path router ...` commands in both `README.md` and `docs/source/en/local_gpu.md` for the features `candle-cuda` and `candle-cuda-turing`, as those were using the flag `--no-default-features` that was ignoring the default features in the `text-embeddings-router` being `candle,http,dynamic-linking`, hence the command was failing as `cudarc` requires to have any linking out of `static-linking`, `dynamic-linking` or `dynamic-loading` for the CUDA Libraries.
Fixes #709 
@Narsil
=> Fix `cargo install` commands for `candle` with CUDA
