README.md, backends/candle/src/lib.rs, core/src/tokenization.rs, router/src/main.rs
=> feat: add support for XLM-RoBERTa

backends/candle/src/compute_cap.rs, router/src/main.rs
=> fix: fix compute cap matching

backends/candle/src/alibi.rs, backends/candle/src/lib.rs, backends/candle/src/models.rs, backends/candle/src/models/bert.rs, backends/candle/src/models/jina.rs
=> feat: support jinaAI variant

.github/workflows/build_75.yaml, Dockerfile-cuda, README.md, backends/candle/src/lib.rs
=> feat: USE_FLASH_ATTENTION env var

.github/workflows/build_documentation.yml, .github/workflows/build_pr_documentation.yml, docs/source/en/_toctree.yml
This PR should fix the following GH action failure: https://github.com/huggingface/text-embeddings-inference/actions/runs/6771685746/job/18402610578
cc @OlivierDehaene
=> GH workflows update: added --not_python_module flag

Cargo.lock, Cargo.toml, backends/candle/Cargo.toml, backends/candle/src/models/bert.rs, backends/candle/src/models/bert_quant.rs, backends/candle/src/models/flash_bert.rs, backends/candle/src/models/jina.rs, backends/python/server/text_embeddings_server/models/default_model.py, backends/python/server/text_embeddings_server/models/flash_bert.py, backends/python/server/text_embeddings_server/utils/tracing.py, core/Cargo.toml, core/src/infer.rs, core/src/queue.rs, core/src/tokenization.rs, load_tests/load.js, router/Cargo.toml, router/src/lib.rs, router/src/server.rs
=> feat: add `normalize` option

core/src/infer.rs, docs/openapi.json, router/src/lib.rs, router/src/server.rs
=> feat: accept batches in predict

.github/workflows/build_documentation.yml, .github/workflows/build_pr_documentation.yml
Doc build only if doc files were changed
cc: @MKhalusova @OlivierDehaene
=> Doc build only if doc files were changed

router/src/main.rs
=> fix: fix tokenizers with both withespace and metaspace

README.md, backends/candle/src/alibi.rs, backends/candle/src/models/bert.rs, backends/candle/src/models/jina.rs, docs/source/en/_toctree.yml, docs/source/en/local_metal.md
=> feat: add support for Metal

backends/candle/build.rs
=> fix(build): remove assert_eq

backends/candle/build.rs, router/src/grpc/server.rs, router/src/http/server.rs
=> fix(router): fix panics on partial_cmp and empty req.texts

README.md, router/src/main.rs
Documents some of the configuration around `--otlp-endpoint` / `OTLP_ENDPOINT`.
@OlivierDehaene
=> added docs for `OTLP_ENDPOINT` around the defaults and format sent

Cargo.lock, core/Cargo.toml, router/src/lib.rs
=> fix: remove modif of tokenizer

core/src/download.rs, router/src/http/server.rs, router/src/lib.rs, router/src/main.rs
=> fix: use st max_seq_length

backends/candle/src/lib.rs, backends/candle/src/models/bert.rs, backends/candle/src/models/flash_bert.rs
=> fix: fix loading of bert classification models

.github/workflows/build_75.yaml, .github/workflows/build_86.yaml, .github/workflows/build_89.yaml, .github/workflows/build_90.yaml, backends/candle/src/lib.rs, backends/candle/src/models/bert.rs, backends/candle/src/models/flash_bert.rs, backends/candle/src/models/flash_distilbert.rs
=> feat: add splade pooling to Bert

README.md, docs/source/en/_toctree.yml, docs/source/en/examples.md
=> readme examples

Cargo.toml
Hihi,
Is there are reason to why `lto` was turned off (3 years ago) and no other optimization were added for releases?
Applying the following optimizations:
- `lto` (Ling time optimizations) over all code (including dependencies)
- Using a single `codegen-unit` to apply optimizations within 1 code unit at build time
- `strip` off symbols, following `debug=0`
@OlivierDehaene OR …
=> Applying `Cargo.toml` optimization options

core/src/infer.rs, core/src/tokenization.rs, docs/openapi.json, proto/tei.proto, router/src/grpc/server.rs, router/src/http/server.rs, router/src/http/types.rs
=> feat: add `/decode` route

proto/tei.proto, router/src/grpc/server.rs
=> feat: add PredictPair to proto

Dockerfile, Dockerfile-cuda-all, sagemaker-entrypoint-cuda-all.sh, sagemaker-entrypoint.sh
Adds CPU Image for sagemaker. Tested both CPU and GPU
=> Add SageMaker CPU images and validate 

backends/candle/src/lib.rs
=> feat(candle): better cuda error

Cargo.lock, Cargo.toml, router/Cargo.toml, router/src/http/server.rs, router/src/http/types.rs
=> feat(router): add base64 encoding_format for OpenAI API

backends/python/server/text_embeddings_server/models/default_model.py
Fixes https://github.com/huggingface/text-embeddings-inference/pull/295#discussion_r1647792109
@OlivierDehaene
=> add cls and mean pooling

Cargo.lock, Cargo.toml, backends/ort/Cargo.toml, backends/ort/src/lib.rs, router/Cargo.toml, router/src/lib.rs
Close #170
Close #404 
Close #405
=> fix: use num_cpus::get to check as get_physical does not check cgroups

.github/workflows/build_rocm.yaml, Dockerfile-rocm, docs/source/en/local_amd_gpu.md
=> ROCM build fixes

.github/workflows/liniting.yaml, Cargo.lock, Dockerfile, Dockerfile-intel, backends/candle/src/layers/cublaslt.rs, backends/candle/src/lib.rs, backends/candle/tests/test_bert.rs, backends/grpc-metadata/src/lib.rs, router/src/lib.rs, rust-toolchain.toml
=> Upgrade TEI.

backends/candle/src/lib.rs, backends/candle/tests/snapshots/test_gte__snowflake_gte_batch.snap, backends/candle/tests/snapshots/test_gte__snowflake_gte_single.snap
=> Fusing both Gte Configs.

Cargo.lock, backends/candle/Cargo.toml, router/src/lib.rs, router/src/logging.rs
=> Small fixup.

flake.nix
=> Fixing the impure flake devShell to be able to run python code.

Cargo.toml
=> Fixing cudarc to the latest unified bindings.

Cargo.toml, docs/openapi.json, docs/source/en/private_models.md, docs/source/en/quick_tour.md, docs/source/en/supported_models.md
=> Preparing for release 1.7.0 (candle update + modernbert).

core/src/tokenization.rs, router/src/grpc/server.rs, router/src/http/server.rs
char with the regular encode method).
Fixes #525 
=> Fixing the tokenization routes token (offsets are in bytes, not in

router/src/http/server.rs, router/src/logging.rs, router/tests/common.rs
=> Fixing the CI (grpc path).

backends/python/server/requirements-hpu.txt, backends/python/server/text_embeddings_server/models/__init__.py
We are going to do modeling in tei instead of depends on optimum-habana for HPU.
=> remove optimum-habana dependency

Cargo.lock, Cargo.toml, docs/openapi.json
=> Preparing the update to 1.7.1

Cargo.lock, Cargo.toml
=> Preparing the release.

backends/candle/src/models/qwen3.rs, flake.lock, flake.nix
=> Make flake work on metal

.github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, backends/grpc-client/src/client.rs, backends/python/server/text_embeddings_server/utils/flash_attn.py, backends/src/lib.rs
This PR updates the following:
- `.github/PULL_REQUEST_TEMPLATE.md` to fix formatting, links, and remove Olivier from the "Who can review?" section to prevent overloading his inbox with notifications
- `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md` to fix both formatting and mentions to Text Generation Inference (TGI) instead of Text Embeddings Inference (TEI)
- Fix wrong mentions to TGI instead of TEI over the codebase
@Narsil
=> Update GitHub templates & fix mentions to Text Embeddings Inference

Dockerfile-intel
We need to upgrade to 1.21.3 for Gaudi 2E device. @regisss , pls help review, thx.
=> HPU upgrade to Synapse 1.21.3

Cargo.lock, Cargo.toml, docs/openapi.json
This PR is prior the v1.8.2 release, and contains the following:
- Update `version` in `Cargo.toml`
- Upload automatically updated `Cargo.lock`
- Export latest `openapi.json` OpenAPI schemas
@Narsil
=> Update `version` to 1.8.2
